[project]
dependencies = [
  "pygame-ce",
  "click",
  "tree-sitter",
  "tree-sitter-python",
]
name = "axedit"
version = "0.1.0.dev"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project.scripts]
axe = "axedit:cli.run"
axedit = "axedit:cli.run"
